### PR TITLE
Separate timing functionality from BaseAgent

### PR DESCRIPTION
**Pull request by Sushant-Chavan**
This pull request removes the timing functionality from the BaseAgent class and implements it in a new class called TimedAgent. Only agents which need to be timed should extend the TimedAgent. All other agents can extend the BaseAgent and not worry about calling _finished()_

The package for storing the common agents is also renamed to maas as discussed in today's lab class.

This pull request also enables an agent to register with the yellow pages with more than one services that it could provide.

### CODE REVIEW

**Comment by Sushant-Chavan** [comment]
@HBRS-MAAS/right-brothers could you please review this pull request?

**Comment by argenos** [comment]
Cc @HBRS-MAAS

**Comment by Sushant-Chavan** [comment]
We have provided more justification for why we think this pull request is important. 

Even if the design choice is not accepted, we believe other fixes to the base agent such as ability to register more than one service-type with the yellow pages could be used.

**Comment by DharminB** [comment]
> Even if the design choice is not accepted, we believe other fixes to the base agent such as ability to register more than one service-type with the yellow pages could be used.

We would be happy to add the feature to register for more than one service type. Would it be possible to make the additions here #54 . This is a pull request for the bug fixes for baseAgent and timeKeeper.

**Comment by argenos** [comment]
What was the conclusion with this pull request? Should this be closed?

**Comment by Sushant-Chavan** [comment]
@argenos This issue can be closed as we concluded that these changes should not be integrated.

**Pull request closed without merging**
