### PR TITLE
WIP: Initial attempt to integrate Customer Agent to Order Processing

### PR DESCRIPTION
**Pull request by widyaaulia**
Problem:
- program stuck when the order is not feasible
- scheduler wait for accepted_proposal after rejecting the customer

### CODE REVIEW

**Comment by janhavi19** [comment]
We are waiting for the issue #75 to be solved

**Comment by argenos** [comment]
If this is not ready to be merged, it should have WIP on the title

**Comment by AhmedFaisal95** [comment]
Hi @argenos .

We were wondering if this was merged by mistake since it has WIP on the title and should have presumably been left open.
@Sushant-Chavan had requested some changes above, since we believed merging this would cause problems to everyone. This is because the team has mentioned some problems in their comment.

**Comment by argenos** [comment]
This was merged because the merge request was merged into develop. If a fix is pushed in the next few hours, I can also merge it.

**Pull request merged**
