### PR TITLE
Add small scenario files

### PR DESCRIPTION
**Pull request by argenos**
@HBRS-MAAS/ws18 I believe the new scenario generator is almost working. Please take a look at the files I just pushed and try to test with them. Things to note: 
* All clients, bakeries, and delivery companies have location as `null`, but their locations are correctly displayed in the `street-network.json` file 
* The street network currently is fully-connected, but this will change... there won't be four edges for every single node. The display does not match their "real distance", but hopefully it gives you a clue of the distribution of nodes.  
* I have not checked anything regarding the recipes, so there may be some inconsistencies there, let me know asap if you find one. 

Let me know if you run into problems, or if you find some errors in this. If there are no comments, I will merge this to `master` on Friday evening.

### CODE REVIEW

**Comment by AhmedFaisal95** [comment]
Hi @argenos.
This is regarding the street-network.json file. In the old one, the "source" and "target" fields in the links/edges JSON objects stored the source and target nodes' IDs (guids), while this one appears to store their x and y coordinates **as a list** in the same fields instead.

This may force us to change some of the logic in the street network, since we rely on node IDs to construct the directed graph. Is it possible for us to revert the old format?

**Comment by argenos** [comment]
@AhmedFaisal95 This is actually a bug! I caught it for the nodes, which do have the format you mention, but didn’t see it when the edges where created. They both should have **x** and **y** fields. Will fix this tomorrow. Good catch!

**Comment by argenos** [comment]
@AhmedFaisal95 the fix was not as complicated as I thought, please let me know if that works for you

**Comment by anenriquez** [comment]
Regarding the steps in the recipes. Which are the steps that define the start and end of a production stage?  Is it: 

- DoughPreparation: from kneading to proofing

- Baking: from baking to cooling
- Packaging: the next step from cooling till the last step 

Each stage might have intermediate steps, but are the boundaries like the ones mentioned above? In that case, in bakeries.json, should cooling be before proofing?

Thanks!

**Comment by DharminB** [comment]
@argenos Just to be absolutely sure, 
- the heating and cooling rate are in degree celsius per minute
- we should take ceiling of the number of hours required to heat or cool objects

Also, there is contradictory information regarding cooling of the products. For example for `broetchen`, the `coolingDuration` in `recipe` is 6 (hours, we assume) and the `coolingRate` is 6 (degree celsuis per minute, we assume), `bakingTemp` is 190 and `boxingTemp` is 40 (degree celsius, we assume). The temperature difference is 150 degree celsius. If it cools down 6 degrees in a minute, then it will take 25 minutes to cool down 150 degree celsius. Rounding this up to 1 hour, will still contradict with 6 hour cooling duration. On the other hand, if we assume that the rates are degree celsius per 15 minutes, then it will take 7 hours (rounding from 6 hours 15 minutes) to cool that 150 degree difference. This is also contradictary. We (@HBRS-MAAS/right-brothers ) propose that `boxingTemp` and `coolingRate` be removed. This will solve the contradiction problem by providing only one source of information (`coolingDuration` in `recipe`).

**Comment by argenos** [comment]
>     the heating and cooling rate are in degree celsius per minute
>     we should take ceiling of the number of hours required to heat or cool objects

This depends on the implementation of the time step that was being discussed in #39.

> Also, there is contradictory information regarding cooling of the products. For example for broetchen, the coolingDuration in recipe is 6 (hours, we assume)

I belive this is after baking (the breads vs the air), and I would keep it as time-steps (again related to #39).

> and the coolingRate is 6 (degree celsuis per minute, we assume),

This is for the oven, not the breads. Same thing for heating rate.

> bakingTemp is 190 and boxingTemp is 40 (degree celsius, we assume).The temperature difference is 150 degree celsius. If it cools down 6 degrees in a minute, then it will take 25 minutes to cool down 150 degree celsius.

This is a bug. The PDF says "After baking, the product must cool before it can be boxed and delivered. The minimal cooling time is proportional to (baking temperature minus 40° Celsius)."

> Rounding this up to 1 hour, will still contradict with 6 hour cooling duration. On the other hand, if we assume that the rates are degree Celsius per 15 minutes, then it will take 7 hours (rounding from 6 hours 15 minutes) to cool that 150 degree difference. This is also contradictory. We (@HBRS-MAAS/right-brothers ) propose that boxingTemp and coolingRate be removed. This will solve the contradiction problem by providing only one source of information (coolingDuration in recipe).

Cooling duration for the bread (considering degrees per time step) and boxingTemp will be fixed according to the specs of the PDF. The "coolingRate" mentioned in the recipe will be removed. The only relevant coolingRate is the one for the ovens, which will remain in place. 

Let me know if that answers all your questions.

**Comment by argenos** [comment]
> Hello @argenos it seems the bakery scenarios do not have information about the slots in the ovens. > Should we assume that each oven has 4 slots?

Yes, for now let's assume each oven has 4 tray slots.

> I forgot to mention that the bakeries.json does have "breadsPerOven" according to the product. If we assume there are 4 slots in an oven, we can get the breadsPerSlot.

This refers to the number of breads per tray. I could rename that but then everyone has to update their parsing of the scenario file. Let me know what you prefer.

> Regarding the steps in the recipes. Which are the steps that define the start and end of a production stage? Is it:
>
>     DoughPreparation: from kneading to proofing
>
>     Baking: from baking to cooling
>
>     Packaging: the next step from cooling till the last step
>
> Each stage might have intermediate steps, but are the boundaries like the ones mentioned above? In that case, in bakeries.json, should cooling be before proofing?

I did not have time to fully check this, but in short, yes. Everything between kneading and proofing (inclusive) is dough preparation. Everything between baking and cooling (inclusive) is in the baking stage, and everything **after** cooling is in packaging.

Cooling shouldn't happen before proofing, do you have a line number where that's happening in bakeries.json?

**Comment by argenos** [comment]
@DharminB the fixes related to the cooling duration, baking and boxing temperature are in the new version I just pushed.

**Comment by AhmedFaisal95** [comment]
> @AhmedFaisal95 the fix was not as complicated as I thought, please let me know if that works for you

@argenos Thanks for the prompt reply. 
Some changes also had to be done to reflect the shift from using floats for location coordinates to using integers. Apart from that, your fix has solved the prior issue.

**Comment by anenriquez** [comment]
> This refers to the number of breads per tray. I could rename that but then everyone has to update their parsing of the scenario file. Let me know what you prefer.
> 
To prevent everyone from having to change their parsers I think we should keep the name  "breadsPerOven". 

> Cooling shouldn't happen before proofing, do you have a line number where that's happening in bakeries.json?
>
Coolling is before proofing in the `sample/bakeries.json` (line 32)  but not in `small/bakeries.json.` My bad, we were testing with `sample/bakeries.json` and not with `small/bakeries.json`. Just to clarify, is  `small/bakeries.json` the one we should use for testing?

**Comment by argenos** [comment]
@anenriquez yes, this pull request is removing the `sample` scenario to avoid confusion.

**Comment by DharminB** [comment]
> Let me know if that answers all your questions.

> @DharminB the fixes related to the cooling duration, baking and boxing temperature are in the new version I just pushed.

Yes, Thank you. The fix solves our doubts.

**Comment by argenos** [comment]
Since there are no more pending questions, I’ll merge to master. @HBRS-MAAS the merged scenario should be the one used for assignment 4 and 5, which you’ll present on Wednesday

**Comment by janl1992** [comment]
Hi Argentina

Sorry for late commenting on this issue. In every recipe item preparation step and resting step is mentioned 2 times. Is this intended? Here an example:
"steps": [
            {
              "duration": 11,
              "action": "kneading"
            },
            {
              "duration": 11,
              "action": "sheeting"
            },
            {
              "duration": 6,
              "action": "twisting"
            },
            {
              "duration": 8,
              "action": "filling"
            },
            {
              "duration": 7,
              "action": "item preparation"
            },
            {
              "duration": 15,
              "action": "resting"
            },
            {
              "duration": 6,
              "action": "proofing"
            },
            {
              "duration": 14,
              "action": "baking"
            },
            {
              "duration": 5,
              "action": "filling"
            },
            {
              "duration": 8,
              "action": "frying"
            },
            {
              "duration": 2,
              "action": "cooling"
            },
            {
              "duration": 8,
              "action": "item preparation"
            },
            {
              "duration": 10,
              "action": "filling"
            },
            {
              "duration": 13,
              "action": "resting"
            },
            {
              "duration": 5,
              "action": "sprinkling"
            },
            {
              "duration": 12,
              "action": "decorating"
            }
          ]

**Comment by argenos** [comment]
Yeah, regardless of the intermediate actions, your stage should do everything between kneading and proofing if it’s dough preparation. Between baking and cooling, it’s baking stage and the rest is packaging.

**Pull request merged**
