### PR TITLE
Proofer agent

### LINKED ISSUE #29: Dough preparation interfaces
Two pull requests are needed: 
- [ ]  docs/messages/proofer.md containing the input and output messages
- [ ]  the proofer agent, which inherits from the base class

### PR DESCRIPTION
**Pull request by anenriquez**
Adding the Proofer Agent. This pull request closes #29

### CODE REVIEW

**Comment by argenos** [comment]
The Travis build is failing, you need to fix this before I can merge

**Comment by anenriquez** [comment]
Sounds reasonable. We'll add the quantity fild to the output message.

**Comment by janl1992** [comment]
By now dough preparation stage does not receive dummy order messages. As per my understanding the messages are created from Dough Manager. Moreover I see no attempt to run the whole interface agent on several computer.
Why did you chose to make kneading machine and dough preparation table as an agent? - Because of this more messages are needed (kneading requests , kneading confirms, preparation requests, preparation confirms). From my point of view architecture gets more complex than it needs to be. Is it not enough to make kneading machine and preparation tables as an object?

**Comment by argenos** [comment]
In general the comments should only be about the interface agents. Each team is applying their own architecture and has their own decisions for this, which means your stage will look different to the one from @HBRS-MAAS/mas_maas

**Comment by janl1992** [comment]
Okay. One remark for output message of interface agent (proofer) from @HBRS-MAAS/team_pjt . The Output Message is a JSON Object which means that you have to call an agent in baking stage every time a productType has to be baked. Our proposal is to make a JSON array instead of a JSON object for outgoing messages so that amount of calls to agent in baking stage is reduced.

**Comment by anenriquez** [comment]
The Proofer Agent is already aggregating by product type. The output message contains all orders of a specific product type which is ready to go to the next production stage (i.e. baking).  If we wait until filling up an array (of different products) the production will slow down.

**Comment by argenos** [comment]
@HBRS-MAAS/mas_maas the pull request is outdated, take a look so I can merge

**Pull request merged**
