### PR TITLE
Fix LoadingBayAgent

### PR DESCRIPTION
**Pull request by AhmedFaisal95**
This pull request applies the following fixes to the loading bay agent:

- Fix searching for order processor
- Fix bug in product and box databases updating
- Fix NullPointerException in aggregation of order details

### CODE REVIEW

**Comment by DRealArun** [comment]
I manually added the changes in this pull request to my team's repository but I came across the following error.After the Loading bay receives the first message of boxes, it encounters an exception. Please find the error logs below. Let me know if any more information is needed.

[loader-agent]: Received product boxes from packaging-agent
>>>>> 000.07.40 <<<<<
***  Uncaught Exception for agent loader-agent  ***
        Started sprinkling 20 Donut at time 7
org.json.JSONException: JSONObject["Products"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:782)
        at org.maas.agents.LoadingBayAgent.orderProductsReady(LoadingBayAgent.java:142)
        at org.maas.agents.LoadingBayAgent$ProductDetailsReceiver.action(LoadingBayAgent.java:277)
        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
        at jade.core.Agent.run(Agent.java:1524)
        at java.lang.Thread.run(Thread.java:748)
ERROR: Agent loader-agent died without being properly terminated !!!
State was 2

**Comment by AhmedFaisal95** [comment]
Another fix was applied to address this issue

**Comment by argenos** [comment]
Should this go to develop first?

**Comment by AhmedFaisal95** [comment]
We have tested this with the @HBRS-MAAS/right-brothers team, who had applied the new proposed changes to the TimeKeeper etc. that are on develop, and verified that it works as intended.

If required, this pull request will be submitted to develop first.

**Comment by argenos** [comment]
Should this go to develop first?

**Pull request merged**
