### PR TITLE
Message format baking stage cooling racks

### PR DESCRIPTION
**Pull request by DharminB**
Partially solves #30

### CODE REVIEW

**Comment by anenriquez** [comment]
According to our discussion from yesterday, the Proofer will send to the Baking Interface a message which contains the guid of an order that is ready to be baked.

**Comment by DharminB** [comment]
> According to our discussion from yesterday, the Proofer will send to the Baking Interface a message which contains the guid of an order that is ready to be baked.

Yes, but as far as I know, the input to `cooling_racks` will be from the agents within `baking` stage. `cooling_racks` is mostly only responsible for sending the messages to the next stage (`packaging` stage). Similarly, `proofer` will be receiving messages from some agents from `dough_prep` stage. I might be wrong here, but I believe that the connecting interface agents (`proofer`, `cooling_racks`, `mailbox`, etc) should be used to **send** message to the next stage. Whatever they receive is not really  related to the previous stage at all. When `baking` stage agent called `oven_manager` receives orders from `proofer` it will process this order first. Please correct me if I am making a mistake here @anenriquez

**Comment by anenriquez** [comment]
Ok, I see what you are saying. I thought that the `input_message` defines what a `baking_agent` (not the `cooling_racks` agent,  but the one that receives the message from the `proofer_agent` is expecting. And the `output_message` defines the output of the `cooling_racks` agent. The `input_message` that you defined in this pull request is the input of the `cooling_racks` agent, right?

**Comment by argenos** [comment]
Please check #42 for the FIPA-specific fields, particularly `conversation-id` which is relevant for all messages

**Comment by argenos** [comment]
> According to our discussion from yesterday, the Proofer will send to the Baking Interface a message which contains the guid of an order that is ready to be baked.

@anenriquez Careful! It might be just a few products that are *part* of an order.

**Comment by DharminB** [comment]
> Ok, I see what you are saying. I thought that the `input_message` defines what a `baking_agent` (not the `cooling_racks` agent, but the one that receives the message from the `proofer_agent` is expecting. And the `output_message` defines the output of the `cooling_racks` agent. The `input_message` that you defined in this pull request is the input of the `cooling_racks` agent, right?

Exactly

**Comment by argenos** [comment]
> the connecting interface agents (proofer, cooling_racks, mailbox, etc) should be used to send message to the next stage

@DharminB although this is what the agents are facilitating, this agents are also performing one step in the production process and should be able to process the input from agents in their corresponding stage. Given that their function is mostly queuing products for a while before they are ready for the next stage, the input messages should be standard for everyone imo

**Comment by DharminB** [comment]
> Please check #42 for the FIPA-specific fields, particularly `conversation-id` which is relevant for all messages

We are not expecting any reply from the receiver. There is no "conversation" as it is only one way communication. Should we still add `conversation-id`? 
Additionally, we can add `ontology` to express that the message is in json format, if necessary

**Comment by argenos** [comment]
> I thought we decided that each team can define their own output message of their corresponding interface agents and that push messages are better than pull messages. 

Yes, each agent has its own input and output messages, but those are standard for all teams. The `cooling_racks` will receive the same message regardless of which team uses it, i.e. an interface agent cannot handle different input messages depending on the team who uses them

> This implies that the input for these interface may be different for different teams (rather than being standard). 

Since they are all performing the same task, how would task requirements differ from team to team?

> If you still think, we should change the input message for cooling rack for this reason, we are happy to comply. 

I have no problems for this to be the standard input message *content* for the `cooling_rack` for all teams, if other teams in @HBRS-MAAS need something additionally, then they should request it. 
The changes I requested are independent of the content.

**Comment by DharminB** [comment]
> Yes, each agent has its own input and output messages, but those are standard for all teams. The `cooling_racks` will receive the same message regardless of which team uses it, i.e. an interface agent cannot handle different input messages depending on the team who uses them
> Since they are all performing the same task, how would task requirements differ from team to team?

I think I misunderstood earlier. You are right, `cooling_racks` as an agent will be same no matter who uses it. Previously I understood that all interface agents (of different stages) should be same. Completely my mistake. Sorry for the confusion.

**Comment by argenos** [comment]
> We are not expecting any reply from the receiver. There is no "conversation" as it is only one way communication. Should we still add `conversation-id`? 

Check the [FIPA ACL specification](
http://www.fipa.org/specs/fipa00061/SC00061G.html#_Toc26669715)! It’s not really about expecting a reply, but about the context of what you’re sending, in this case which order they belong to. Check which fields I recommended to #42

**Comment by anenriquez** [comment]
> > According to our discussion from yesterday, the Proofer will send to the Baking Interface a message which contains the guid of an order that is ready to be baked.
> 
> @anenriquez Careful! It might be just a few products that are _part_ of an order.

Thanks! We'll take this into account when we update the pull request of the Proofer messages.

**Comment by emassey2** [comment]
For the loading bay message I think it makes more sense for products to be an array of product objects instead of products being an object itself.

So instead of:
```
{
    "products": {
      String("product_name"): int(quantity),
      String("another_product_name"): int(quantity),
      ...
    }
}
```

It would be something like: 
```
{
    "products" : [
      {
          "bagel" : 3
      },

      {
          "bread" : 5
      }
    ]
}

```

This way we avoid having to transmit key:value pairs for every product (where many quantities will probably be 0) or having a json object with an variable number of key:value pairs.

**Comment by DharminB** [comment]
> For the input of the Cooling racks agent, we think it would be better to have the boxing temperature instead of the cooling duration because we already have the cooling rate. With the cooling rate and the boxing temperature, we could calculate the duration.

We agree with the boxing temperature addition and edit the message and create another pull request. Regarding the cooling rate and cooling duration, we agree, but we would like to wait till the config files are dependable in order to prevent unnecessary changes.

**Comment by DharminB** [comment]
> For the loading bay message I think it makes more sense for products to be an array of product objects instead of products being an object itself.
> 
> ```
> {
>     "products" : [
>       {
>           product_name : "bagel",
>           quantity : 3
>       },
> 
>       {
>           product_name : "bread",
>           quantity : 5
>       }
>     ]
> }
> ```

We agree that it makes more sense if the message was a JSONArray of Product JSONObjects. One of the advantage would be easier addition of more fields. We made the design the way it is because of the config files (specifically `clients.json` has order as products in key value or hashtable format). We assumed it is kept the way it was kept for some well thought out reason. We would be happy to change it as you mention above if it is okay with @argenos . In fact it would be better if it as below.
```
[
      {
          product_name : "bagel",
          quantity : 3
      },
      {
          product_name : "bread",
          quantity : 5
      }
]
```

> This way we avoid having to transmit key:value pairs for every product (where many quantities will probably be 0) or having a json object with an variable number of key:value pairs.

Just to be on the same page, we do not send quantity 0 for any product in the out message of cooling racks. We do, however, have variable number of key value pairs in the hashtable type JSONObject.  Though, it would be the same case if we change the message format to the one proposed above. As in, the message will still contain a variable amount of objects.

**Pull request merged**
